Repository R00ME/roome-admin-be, pull requests merged in 2025-09, with the labels that each got.

#32 :recycle: fix: Admin 프로필 조회 api response 수정(알림 관련 adminId 추가)
  src/main/java/com/roome/admin/roomeadminbe/domain/admin/dto/response/ReadAdminInfoResponse.java
  src/main/java/com/roome/admin/roomeadminbe/domain/admin/service/AdminService.java
Labels: enhancement

#34 :sparkles: feat: 알림 자동 생성 로직 구현 및 기존 로직 정리
  src/main/java/com/roome/admin/roomeadminbe/domain/notification/controller/NotificationController.java
  src/main/java/com/roome/admin/roomeadminbe/domain/notification/dto/NotificationRequestDto.java
  src/main/java/com/roome/admin/roomeadminbe/domain/notification/repository/AdminNotificationRepository.java
  src/main/java/com/roome/admin/roomeadminbe/domain/notification/repository/NotificationRepository.java
  src/main/java/com/roome/admin/roomeadminbe/domain/notification/service/NotificationService.java
Labels: enhancement

#51 Fix/#25 gtag 관련 데이터 저장 및 조회 api 구현
  .gitignore
  src/main/java/com/roome/admin/roomeadminbe/domain/admin/dto/response/AdminResponse.java
  src/main/java/com/roome/admin/roomeadminbe/domain/admin/repository/AdminRepositoryImpl.java
  src/main/java/com/roome/admin/roomeadminbe/domain/apiUsage/controller/ApiUsageController.java
  src/main/java/com/roome/admin/roomeadminbe/domain/apiUsage/dto/response/PointTrendResponse.java
  src/main/java/com/roome/admin/roomeadminbe/domain/apiUsage/dto/response/UserPointTrendResponse.java
  src/main/java/com/roome/admin/roomeadminbe/domain/apiUsage/repository/UserApiUsageRepositoryCustom.java
  src/main/java/com/roome/admin/roomeadminbe/domain/apiUsage/repository/UserApiUsageRepositoryImpl.java
  src/main/java/com/roome/admin/roomeadminbe/domain/apiUsage/service/PointUsageService.java
  src/main/java/com/roome/admin/roomeadminbe/domain/common/entity/PointHistory.java
  src/main/java/com/roome/admin/roomeadminbe/domain/common/entity/PointReason.java
  src/main/java/com/roome/admin/roomeadminbe/domain/common/repository/PointHistoryRepository.java
  src/main/java/com/roome/admin/roomeadminbe/domain/common/repository/PointHistoryRepositoryCustom.java
  src/main/java/com/roome/admin/roomeadminbe/domain/common/repository/PointHistoryRepositoryImpl.java
  src/main/java/com/roome/admin/roomeadminbe/domain/event/controller/FirstComeEventController.java
  src/main/java/com/roome/admin/roomeadminbe/domain/event/dto/EventRegisterRequestDTO.java
  src/main/java/com/roome/admin/roomeadminbe/domain/event/entity/EventStatus.java
  src/main/java/com/roome/admin/roomeadminbe/domain/event/entity/FirstComeEvent.java
  src/main/java/com/roome/admin/roomeadminbe/domain/event/repository/FirstComeEventRepository.java
  src/main/java/com/roome/admin/roomeadminbe/domain/event/repository/FirstComeEventRepositoryImpl.java
  src/main/java/com/roome/admin/roomeadminbe/domain/ga4/Ga4Properties.java
  src/main/java/com/roome/admin/roomeadminbe/domain/ga4/controller/GaController.java
  src/main/java/com/roome/admin/roomeadminbe/domain/ga4/dto/response/ActivityTimeResponse.java
  src/main/java/com/roome/admin/roomeadminbe/domain/ga4/dto/response/FeatureStatResponse.java
  src/main/java/com/roome/admin/roomeadminbe/domain/ga4/dto/response/FeatureUsageResponse.java
  src/main/java/com/roome/admin/roomeadminbe/domain/ga4/dto/response/UserActivityResponse.java
  src/main/java/com/roome/admin/roomeadminbe/domain/ga4/dto/response/UserFeatureStatsResponse.java
  src/main/java/com/roome/admin/roomeadminbe/domain/ga4/dto/response/UserPatternResponse.java
  src/main/java/com/roome/admin/roomeadminbe/domain/ga4/entity/GaFeatureStat.java
  src/main/java/com/roome/admin/roomeadminbe/domain/ga4/entity/GaUserStat.java
  src/main/java/com/roome/admin/roomeadminbe/domain/ga4/repository/GaEventDailyRepositoryCustom.java
  src/main/java/com/roome/admin/roomeadminbe/domain/ga4/repository/GaEventDailyRepositoryImpl.java
  src/main/java/com/roome/admin/roomeadminbe/domain/ga4/repository/GaFeatureStatRepositoryCustom.java
  src/main/java/com/roome/admin/roomeadminbe/domain/ga4/repository/GaFeatureStatRepositoryImpl.java
  src/main/java/com/roome/admin/roomeadminbe/domain/ga4/repository/GaUserPatternRepository.java
  src/main/java/com/roome/admin/roomeadminbe/domain/ga4/repository/GaUserPatternRepositoryImpl.java
  src/main/java/com/roome/admin/roomeadminbe/domain/ga4/repository/GaUserStatRepository.java
  src/main/java/com/roome/admin/roomeadminbe/domain/ga4/repository/GaUserStatRepositoryCustom.java
  src/main/java/com/roome/admin/roomeadminbe/domain/ga4/repository/GaUserStatRepositoryImpl.java
  src/main/java/com/roome/admin/roomeadminbe/domain/ga4/scheduler/GaDailyJob.java
  src/main/java/com/roome/admin/roomeadminbe/domain/ga4/service/GaAggregationService.java
  src/main/java/com/roome/admin/roomeadminbe/domain/ga4/service/GaEventCollectorService.java
  src/main/java/com/roome/admin/roomeadminbe/domain/ga4/service/GaService.java
  src/main/java/com/roome/admin/roomeadminbe/domain/notification/controller/NotificationController.java
  src/main/java/com/roome/admin/roomeadminbe/domain/notification/repository/AdminNotificationRepository.java
  src/main/java/com/roome/admin/roomeadminbe/domain/notification/repository/EmitterRepository.java
  src/main/java/com/roome/admin/roomeadminbe/domain/notification/repository/NotificationRepository.java
  src/main/java/com/roome/admin/roomeadminbe/domain/notification/service/NotificationService.java
  src/main/java/com/roome/admin/roomeadminbe/domain/notification/service/SseService.java
  src/main/java/com/roome/admin/roomeadminbe/domain/ranking/controller/RankingController.java
  src/main/java/com/roome/admin/roomeadminbe/domain/superadmin/service/SuperAdminService.java
  src/main/java/com/roome/admin/roomeadminbe/global/config/GoogleAnalyticsConfig.java
  src/main/java/com/roome/admin/roomeadminbe/global/exception/enumeration/ErrorCode.java
  src/main/java/com/roome/admin/roomeadminbe/global/init/AdminInitializer.java
Labels: bug, enhancement

#52 Fix/#50 관리자 권한 회수 soft delete 후 동일 이메일 초대 로직 수정 및 운영자 목록 정렬 조건 추가
  src/main/java/com/roome/admin/roomeadminbe/domain/admin/entity/Admin.java
  src/main/java/com/roome/admin/roomeadminbe/domain/admin/repository/AdminRepositoryImpl.java
  src/main/java/com/roome/admin/roomeadminbe/domain/superadmin/service/SuperAdminService.java
Labels: enhancement

#57 Fix/#56 운영자 목록 도커 반영 후 api 호출 실패 해결
  .gitignore
  src/main/java/com/roome/admin/roomeadminbe/domain/admin/repository/AdminRepositoryImpl.java
  src/main/java/com/roome/admin/roomeadminbe/domain/superadmin/service/SuperAdminService.java
  src/main/java/com/roome/admin/roomeadminbe/global/exception/enumeration/ErrorCode.java
Labels: bug
